# Generated by Django 4.2.4 on 2024-11-04 21:51

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', app.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_operand', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(choices=[('dr', 'Draft'), ('del', 'Deleted'), ('f', 'Formed'), ('c', 'Completed'), ('r', 'Rejected')], default='dr', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asks_created', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks_moderated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('operator_name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('d', 'Deleted')], default='a', max_length=7)),
                ('value_0', models.BooleanField(default=False, null=True)),
                ('value_A', models.BooleanField(default=False, null=True)),
                ('value_B', models.BooleanField(default=False, null=True)),
                ('value_AB', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AskOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_operand', models.BooleanField(default=False, null=True)),
                ('result', models.BooleanField(default=None, null=True)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ask')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='askoperation',
            constraint=models.UniqueConstraint(fields=('ask', 'operation'), name='unique_ask_operation'),
        ),
        migrations.AddConstraint(
            model_name='ask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'dr')), fields=('creator',), name='unique_draft_per_user'),
        ),
    ]
