# Generated by Django 4.2.4 on 2024-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_date_joined_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активен ли пользователь?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, null=True, verbose_name='Является ли пользователь менеджером?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True, verbose_name='Является ли пользователь админом?'),
        ),
    ]
