# Generated by Django 4.2.4 on 2024-10-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_result_0_operation_value_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='description',
            new_name='operator_name',
        ),
    ]
