# Generated by Django 4.2.4 on 2024-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_description_operation_operator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(default='Описание'),
            preserve_default=False,
        ),
    ]
