# Generated by Django 4.2.4 on 2024-10-08 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_number', models.IntegerField()),
                ('status', models.CharField(choices=[('dr', 'Draft'), ('del', 'Deleted'), ('f', 'Formed'), ('c', 'Completed'), ('r', 'Rejected')], default='dr', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks_created', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asks_moderated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('d', 'Deleted')], default='a', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='AskOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ask')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='askoperation',
            constraint=models.UniqueConstraint(fields=('ask', 'operation'), name='unique_ask_operation'),
        ),
        migrations.AddConstraint(
            model_name='ask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('creator',), name='unique_draft_per_user'),
        ),
    ]
