# Generated by Django 4.2.4 on 2024-10-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ask_first_operand_askoperation_second_operand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askoperation',
            name='user',
        ),
    ]
